Add emoji support
nhcarrigan/we-love-matt pull request #11
Opened 2020-10-07 09:57 UTC by alphaX86

# Pull Request

## Description:

I've added emoji support for the bot in any case. Do test them to find out

## Related Issue:

No, it's not. It's just a feature request

2020-10-07 09:59 UTC, alphaX86 commented on index.ts
> +    message.content.includes(:regional_indicator_m::a::regional_indicator_t::regional_indicator_t:)
Emoji part

2020-10-07 11:17 UTC, SijmenHuizenga commented on index.ts
> +    message.content.includes(:regional_indicator_m::a::regional_indicator_t::regional_indicator_t:)
Missing quotes?

Should probably be

```
    message.content.includes(":regional_indicator_m::regional_indicator_a::regional_indicator_t::regional_indicator_t:") ||
    message.content.includes(":regional_indicator_m::a::regional_indicator_t::regional_indicator_t:")
```

2020-10-07 12:35 UTC, alphaX86 commented on index.ts
> +    message.content.includes(:regional_indicator_m::a::regional_indicator_t::regional_indicator_t:)
OK will change that! 👍

2020-10-07 12:56 UTC, alphaX86 commented
Change made and Lint test passed! 😄

2020-10-07 12:57 UTC, alphaX86 commented on index.ts
> +    )
Added code

2020-10-07 14:55 UTC, nhcarrigan requested changes

2020-10-07 14:55 UTC, nhcarrigan commented on index.ts
> +    )
```suggestion
    message.content.includes("🇲 🇦 🇹 🇹") ||
    message.content.includes("🇲 🅰️ 🇹 🇹")
```
Were you able to get the `:regional_indicator:` strings to work locally? I pulled this down and it wouldn't work - Discord does some funko stuff behind the scenes with emoji. 
However, I *did* get it to recognise the message if I used the `unicode` emoji here in the code instead of the Discord call string.

2020-10-07 14:59 UTC, alphaX86 commented on index.ts
> +    )
Oh, I didn't think of that bro. Well, IDK if UNICODE works, but yeah. I'll look on to it...

And don't close this PR, I'll do the changes later tomorrow in my Time Zone as I'm so tired lol.

2020-10-07 15:00 UTC, nhcarrigan commented on index.ts
> +    )
The unicode here in `.includes` provided the functionality on my local instance. 😁 

No worries, get some sleep!

2020-10-08 00:21 UTC, nhcarrigan commented
Tweaked the code a bit for easier contributing, so this will need a rebase as well. 🙂

2020-10-08 01:56 UTC, alphaX86 commented
Oh...OK! 👍

2020-10-08 15:50 UTC, alphaX86 commented
I've opened #15 since I rebased the repo. So yeah, I'm closing this PR

2020-10-08 15:50 UTC, closed without merging